project:
  type: website
  execute-dir: project
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "Angel Chen"
  favicon: images/pigeon.png
  repo-url: https://github.com/angelchen7/angelchen7.github.io
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Home üè†"
      - about.qmd
      - selected.qmd
      - publications.qmd
      - text: "Other Products"
        menu: 
          - workshops.qmd
          - packages.qmd
          - projects.qmd
    right:
      - icon: envelope-fill
        href: mailto:angel777chen@gmail.com
      - icon: file-text-fill
        href: https://github.com/angelchen7/angelchen7.github.io/blob/main/files/AngelChenCV_July2024.pdf
      - icon: linkedin
        href: https://www.linkedin.com/in/angel-chen77/
      - icon: github
        href: https://github.com/angelchen7/

format:
  html:
    theme:
       light: light_theme.scss
       dark: dark_theme.scss
    mainfont: Lato
    toc: true
    link-external-newwindow: true
    link-external-icon: false